# Generated by Django 4.2 on 2024-10-23 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='present',
            new_name='award',
        ),
        migrations.AlterField(
            model_name='habit',
            name='action',
            field=models.CharField(max_length=200, verbose_name='Выполняемое действие'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='complete_time',
            field=models.DurationField(verbose_name='Время на выполнение привычки'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='habit_time',
            field=models.DateTimeField(verbose_name='Дата и время выполнения привычки'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='is_nice',
            field=models.BooleanField(default=False, verbose_name='Приятноить привычка'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Публичность привычки'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='location',
            field=models.CharField(default='Дома', max_length=200, verbose_name='Место выполнения привычки'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='period',
            field=models.PositiveIntegerField(verbose_name='Период выполнения привычки'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='related_habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='Связанность привычки'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто выполняет привычку'),
        ),
    ]
